name       : baloo-widgets
version    : 21.08.0
release    : 52
source     :
    - https://cdn.download.kde.org/stable/release-service/21.08.0/src/baloo-widgets-21.08.0.tar.xz : 9ef1dc516900e3a4c3e7f382b3cd34df36dcbb4f089d494a28b30b5072a6c741
homepage   : https://community.kde.org/Baloo
license    : LGPL-2.1-only
component  : desktop.kde
summary    : Widgets for the Baloo search engine
description: |
    Widgets for the Baloo search engine.
optimize   : lto
builddeps  :
    - baloo-devel
    - kio-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
