name       : baloo-widgets
version    : 21.04.1
release    : 49
source     :
    - https://cdn.download.kde.org/stable/release-service/21.04.1/src/baloo-widgets-21.04.1.tar.xz : ea3247575b8825237b61009c9764f788e80324783f8f13cf20a5bcfabdcdd72e
homepage   : https://community.kde.org/Baloo
license    : LGPL-2.1-only
component  : desktop.kde
summary    : Widgets for the Baloo search engine
description: |
    Widgets for the Baloo search engine.
optimize   : lto
builddeps  :
    - baloo-devel
    - kio-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
