name       : baloo-widgets
version    : 17.04.1
release    : 1
source     :
    - https://download.kde.org/stable/applications/17.04.1/src/baloo-widgets-17.04.1.tar.xz : 3a181dba19586cd26fa009b91abf3428df00f8beb9afb6e7959877d6b58f8069
license    : LGPL-2.1
component  : desktop.kde
summary    : Widgets for the Baloo search engine
description: |
    Widgets for the Baloo search engine.
builddeps  :
    - pkgconfig(Baloo)
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kconfig-devel
    - kfilemetadata-devel
    - ki18n-devel
    - kio-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
