name       : baloo-widgets
version    : 20.04.0
release    : 35
source     :
    - https://cdn.download.kde.org/stable/release-service/20.04.0/src/baloo-widgets-20.04.0.tar.xz : 8ce3bdafd8b3598799d5303af483295625db7a7b66b08cff2d6c3d35df759853
homepage   : https://community.kde.org/Baloo
license    : LGPL-2.1
component  : desktop.kde
optimize   : lto
summary    : Widgets for the Baloo search engine
description: |
    Widgets for the Baloo search engine.
builddeps  :
    - pkgconfig(Baloo)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kconfig-devel
    - kfilemetadata-devel
    - ki18n-devel
    - kio-devel
    - kwindowsystem-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
