name       : baloo-widgets
version    : 18.08.3
release    : 16
source     :
    - https://cdn.download.kde.org/stable/applications/18.08.3/src/baloo-widgets-18.08.3.tar.xz : 3a8583adbd9bf9f1c38918c11972ef8aa2db5e94bee36695823c1360a7d47d1c
license    : LGPL-2.1
component  : desktop.kde
optimize   : lto
summary    : Widgets for the Baloo search engine
description: |
    Widgets for the Baloo search engine.
builddeps  :
    - pkgconfig(Baloo)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kconfig-devel
    - kfilemetadata-devel
    - ki18n-devel
    - kio-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
