name       : baloo-widgets
version    : 19.12.1
release    : 31
source     :
    - https://cdn.download.kde.org/stable/release-service/19.12.1/src/baloo-widgets-19.12.1.tar.xz : a9fb3a136267bb0089192f7bc523903bd304e528160d9f653ccd052b4a8c110c
homepage   : https://community.kde.org/Baloo
license    : LGPL-2.1
component  : desktop.kde
optimize   : lto
summary    : Widgets for the Baloo search engine
description: |
    Widgets for the Baloo search engine.
builddeps  :
    - pkgconfig(Baloo)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kconfig-devel
    - kfilemetadata-devel
    - ki18n-devel
    - kio-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
