name       : baloo-widgets
version    : 18.08.1
release    : 14
source     :
    - https://cdn.download.kde.org/stable/applications/18.08.1/src/baloo-widgets-18.08.1.tar.xz : b7f3bf10e2aa8e30ae7230c781c2d3cd1e71290e1df6f126dee8d7a9803468a9
license    : LGPL-2.1
component  : desktop.kde
optimize   : lto
summary    : Widgets for the Baloo search engine
description: |
    Widgets for the Baloo search engine.
builddeps  :
    - pkgconfig(Baloo)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kconfig-devel
    - kfilemetadata-devel
    - ki18n-devel
    - kio-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
