name       : baloo-widgets
version    : 18.12.1
release    : 18
source     :
    - https://cdn.download.kde.org/stable/applications/18.12.1/src/baloo-widgets-18.12.1.tar.xz : 83d716d774a77fba1fad1aa9cf88e6c06e3c20682bc904371071aa957fe8af2b
license    : LGPL-2.1
component  : desktop.kde
optimize   : lto
summary    : Widgets for the Baloo search engine
description: |
    Widgets for the Baloo search engine.
builddeps  :
    - pkgconfig(Baloo)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kconfig-devel
    - kfilemetadata-devel
    - ki18n-devel
    - kio-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
