name       : baloo-widgets
version    : 21.08.2
release    : 54
source     :
    - https://cdn.download.kde.org/stable/release-service/21.08.2/src/baloo-widgets-21.08.2.tar.xz : 5d212156b9f39aa4111b7bb0974e1bfcacb90f30d3f9cdd308a6f700f1c668ba
homepage   : https://community.kde.org/Baloo
license    : LGPL-2.1-only
component  : desktop.kde
summary    : Widgets for the Baloo search engine
description: |
    Widgets for the Baloo search engine.
optimize   : lto
builddeps  :
    - baloo-devel
    - kio-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
