name       : baloo-widgets
version    : 23.04.2
release    : 67
source     :
    - https://cdn.download.kde.org/stable/release-service/23.04.2/src/baloo-widgets-23.04.2.tar.xz : d3a01392811ab0a6e850e0058518a95617ad50a2e2bb8c553931130a13a98b66
homepage   : https://community.kde.org/Baloo
license    : LGPL-2.1-only
component  : desktop.kde
summary    : Widgets for the Baloo search engine
description: |
    Widgets for the Baloo search engine.
optimize   : lto
builddeps  :
    - baloo-devel
    - kio-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
