name       : baloo-widgets
version    : 19.08.1
release    : 26
source     :
    - https://cdn.download.kde.org/stable/applications/19.08.1/src/baloo-widgets-19.08.1.tar.xz : 83429a70de735edc4714dc1b6f1a5a8c7d3d68a93165e98d2cadeecafa82af7b
license    : LGPL-2.1
component  : desktop.kde
optimize   : lto
summary    : Widgets for the Baloo search engine
description: |
    Widgets for the Baloo search engine.
builddeps  :
    - pkgconfig(Baloo)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kconfig-devel
    - kfilemetadata-devel
    - ki18n-devel
    - kio-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
