name       : baloo-widgets
version    : 19.12.0
release    : 30
source     :
    - https://cdn.download.kde.org/stable/release-service/19.12.0/src/baloo-widgets-19.12.0.tar.xz : c16c248c20b2f4fe344b90283070a316eaef7e03b3b4e5f3b9a102b89977672e
license    : LGPL-2.1
component  : desktop.kde
optimize   : lto
summary    : Widgets for the Baloo search engine
description: |
    Widgets for the Baloo search engine.
builddeps  :
    - pkgconfig(Baloo)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kconfig-devel
    - kfilemetadata-devel
    - ki18n-devel
    - kio-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
