name       : baloo-widgets
version    : 22.04.3
release    : 62
source     :
    - https://cdn.download.kde.org/stable/release-service/22.04.3/src/baloo-widgets-22.04.3.tar.xz : d73a67e07189c10ff633f7c0cac40f4d7ac83debeea5d83f6fd7b745b35d0401
homepage   : https://community.kde.org/Baloo
license    : LGPL-2.1-only
component  : desktop.kde
summary    : Widgets for the Baloo search engine
description: |
    Widgets for the Baloo search engine.
optimize   : lto
builddeps  :
    - baloo-devel
    - kio-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
