name       : baloo-widgets
version    : 19.12.2
release    : 32
source     :
    - https://cdn.download.kde.org/stable/release-service/19.12.2/src/baloo-widgets-19.12.2.tar.xz : ccc2df948f1d6245593ab1c6082b347e8da45bc502df0557caf0e17040c0bbc8
homepage   : https://community.kde.org/Baloo
license    : LGPL-2.1
component  : desktop.kde
optimize   : lto
summary    : Widgets for the Baloo search engine
description: |
    Widgets for the Baloo search engine.
builddeps  :
    - pkgconfig(Baloo)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kconfig-devel
    - kfilemetadata-devel
    - ki18n-devel
    - kio-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
