name       : baloo-widgets
version    : 20.12.3
release    : 47
source     :
    - https://cdn.download.kde.org/stable/release-service/20.12.3/src/baloo-widgets-20.12.3.tar.xz : 113bec52f93b0c18f62e0c5814a8221ea1c8e2f26e6079937d337564fffbf633
homepage   : https://community.kde.org/Baloo
license    : LGPL-2.1-only
component  : desktop.kde
summary    : Widgets for the Baloo search engine
description: |
    Widgets for the Baloo search engine.
optimize   : lto
builddeps  :
    - baloo-devel
    - kio-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
