name       : baloo-widgets
version    : 23.04.1
release    : 66
source     :
    - https://cdn.download.kde.org/stable/release-service/23.04.1/src/baloo-widgets-23.04.1.tar.xz : 00461e9ca746ba77f164c57025f16da8baa3f5e1695730f153c26f17bfeed747
homepage   : https://community.kde.org/Baloo
license    : LGPL-2.1-only
component  : desktop.kde
summary    : Widgets for the Baloo search engine
description: |
    Widgets for the Baloo search engine.
optimize   : lto
builddeps  :
    - baloo-devel
    - kio-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
