name       : baloo-widgets
version    : 17.12.3
release    : 8
source     :
    - https://cdn.download.kde.org/stable/applications/17.12.3/src/baloo-widgets-17.12.3.tar.xz : 10956500e389cce6b043fbda7bdc16916cda75548f285268025d72dc5546c1be
license    : LGPL-2.1
component  : desktop.kde
optimize   : lto
summary    : Widgets for the Baloo search engine
description: |
    Widgets for the Baloo search engine.
builddeps  :
    - pkgconfig(Baloo)
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kconfig-devel
    - kfilemetadata-devel
    - ki18n-devel
    - kio-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
