name       : baloo-widgets
version    : 19.08.2
release    : 27
source     :
    - https://cdn.download.kde.org/stable/applications/19.08.2/src/baloo-widgets-19.08.2.tar.xz : 529f3b587098eb9b7d1aaa8b311f98c58d16ed88384fa0900f9fb9f8e242c070
license    : LGPL-2.1
component  : desktop.kde
optimize   : lto
summary    : Widgets for the Baloo search engine
description: |
    Widgets for the Baloo search engine.
builddeps  :
    - pkgconfig(Baloo)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kconfig-devel
    - kfilemetadata-devel
    - ki18n-devel
    - kio-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
