name       : baloo-widgets
version    : 21.04.0
release    : 48
source     :
    - https://cdn.download.kde.org/stable/release-service/21.04.0/src/baloo-widgets-21.04.0.tar.xz : 3996d5741c2f88c5e32ecd672148f7d255a863a4c355e92f120ae67c2c48c523
homepage   : https://community.kde.org/Baloo
license    : LGPL-2.1-only
component  : desktop.kde
summary    : Widgets for the Baloo search engine
description: |
    Widgets for the Baloo search engine.
optimize   : lto
builddeps  :
    - baloo-devel
    - kio-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
