name       : baloo-widgets
version    : 18.12.0
release    : 17
source     :
    - https://cdn.download.kde.org/stable/applications/18.12.0/src/baloo-widgets-18.12.0.tar.xz : 8fb291d02eb13315f1544d2523d50a9107f8ea5a564f7611e7e2b5240a0507eb
license    : LGPL-2.1
component  : desktop.kde
optimize   : lto
summary    : Widgets for the Baloo search engine
description: |
    Widgets for the Baloo search engine.
builddeps  :
    - pkgconfig(Baloo)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kconfig-devel
    - kfilemetadata-devel
    - ki18n-devel
    - kio-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
